#!/bin/bash
set -ue
if [[ -n "$( pwd | grep -o -P ' ' )" ]]; then
	echo "Warning! Working directory contains spaces, virtualenv might have problems with it!"
fi
if [ ! -d venv ]; then
	virtualenv --verbose venv
fi
./venv/bin/easy_install markdown html5lib python-openid South psycopg2 mysql-python python-memcached django==1.3.1 django-debug-toolbar django-endless-pagination
echo "Virtualenv installed to ./venv"
